---
version: "2"
run:
  build-tags:
    - "test"
linters:
  default: "all"
  disable:
    - "depguard"
    - "dupl"
    - "err113"
    - "exhaustruct"
    - "funlen"
    - "gochecknoglobals"
    - "testpackage"
    - "cyclop"
  settings:
    mnd:
      ignored-numbers:
        - "0o644"
        - "0o755"
        - "42"
formatters:
  enable:
    - "gci"
    - "gofmt"
    - "gofumpt"
    - "goimports"
    - "golines"
  settings:
    golines:
      max-len: 120
...
