---
run:
  build-tags:
    - "test"
linters:
  enable-all: true
  disable:
    - "testpackage"
    - "exhaustruct"
    - "err113"
    - "depguard"
    - "funlen"
    - "dupl"
    - "gochecknoglobals"
    - "tenv"
linters-settings:
  mnd:
    ignored-numbers:
      - "0o644"
      - "0o755"
      - "42"
  goconst:
    ignore-tests: true
...
