---
version: 2

before:
  hooks:
    - "go mod tidy"

builds:
  - env:
      - "CGO_ENABLED=0"
    goos:
      - "darwin"
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
    ldflags:
      - "-s -w -X github.com/erNail/verscout/cmd.version={{ .Version }}"

# Container Image build
kos:
  - repository: "ernail/verscout"
    base_image: "alpine:3.21.2"
    tags:
      - "{{ .Version }}"
    bare: true
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
      - "linux/arm64"

brews:
  - name: "verscout"
    caveats: "Run `verscout -h` to get started!"
    homepage: "https://github.com/erNail/verscout"
    description: >
      Find the latest version tag, calculate the next version, print to STDOUT
      - no tagging, no bumping, no changelog, no publishing.
    license: "MIT"
    commit_msg_template: "chore: Update brew formula for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: "erNail"
      name: "homebrew-tap"
      branch: "feature/formula-update"
      token: "{{ .Env.HOMEBREW_TAP_ERNAIL_GITHUB_TOKEN }}"
      pull_request:
        enabled: true

release:
  draft: true
...
